// <auto-generated />
using EFCoreCodeFirstOneToManyDZ.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreCodeFirstOneToManyDZ.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCoreCodeFirstOneToManyDZ.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("EFCoreCodeFirstOneToManyDZ.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdProduct")
                        .HasColumnType("int")
                        .HasColumnName("id_product");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("IdProduct");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("EFCoreCodeFirstOneToManyDZ.Models.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Name")
                        .HasColumnType("int")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Producer", (string)null);
                });

            modelBuilder.Entity("EFCoreCodeFirstOneToManyDZ.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdCategory")
                        .HasColumnType("int")
                        .HasColumnName("id_category");

                    b.Property<int?>("IdProducer")
                        .HasColumnType("int")
                        .HasColumnName("id_producer");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<double?>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.Property<byte[]>("ProductPicture")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("productPicture");

                    b.Property<string>("ProductPicturePath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("productPicturePath");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("IdCategory");

                    b.HasIndex("IdProducer");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("EFCoreCodeFirstOneToManyDZ.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdProduct")
                        .HasColumnType("int")
                        .HasColumnName("id_product");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("IdProduct");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("EFCoreCodeFirstOneToManyDZ.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Access")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdOrder")
                        .HasColumnType("int")
                        .HasColumnName("id_order");

                    b.Property<int?>("IdReview")
                        .HasColumnType("int")
                        .HasColumnName("id_review");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PicturePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdOrder");

                    b.HasIndex("IdReview");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("EFCoreCodeFirstOneToManyDZ.Models.Order", b =>
                {
                    b.HasOne("EFCoreCodeFirstOneToManyDZ.Models.Product", "IdProductNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("IdProduct")
                        .HasConstraintName("FK_Order_Product");

                    b.Navigation("IdProductNavigation");
                });

            modelBuilder.Entity("EFCoreCodeFirstOneToManyDZ.Models.Product", b =>
                {
                    b.HasOne("EFCoreCodeFirstOneToManyDZ.Models.Category", "IdCategoryNavigation")
                        .WithMany("Products")
                        .HasForeignKey("IdCategory")
                        .HasConstraintName("FK_Product_Category");

                    b.HasOne("EFCoreCodeFirstOneToManyDZ.Models.Producer", "IdProducerNavigation")
                        .WithMany("Products")
                        .HasForeignKey("IdProducer")
                        .HasConstraintName("FK_Product_Producer");

                    b.Navigation("IdCategoryNavigation");

                    b.Navigation("IdProducerNavigation");
                });

            modelBuilder.Entity("EFCoreCodeFirstOneToManyDZ.Models.Review", b =>
                {
                    b.HasOne("EFCoreCodeFirstOneToManyDZ.Models.Product", "IdProductNavigation")
                        .WithMany("Reviews")
                        .HasForeignKey("IdProduct")
                        .HasConstraintName("FK_Review_Product");

                    b.Navigation("IdProductNavigation");
                });

            modelBuilder.Entity("EFCoreCodeFirstOneToManyDZ.Models.User", b =>
                {
                    b.HasOne("EFCoreCodeFirstOneToManyDZ.Models.Order", "IdOrderNavigation")
                        .WithMany("Users")
                        .HasForeignKey("IdOrder")
                        .HasConstraintName("FK_User_Order");

                    b.HasOne("EFCoreCodeFirstOneToManyDZ.Models.Review", "IdReviewNavigation")
                        .WithMany("Users")
                        .HasForeignKey("IdReview")
                        .HasConstraintName("FK_User_Review");

                    b.Navigation("IdOrderNavigation");

                    b.Navigation("IdReviewNavigation");
                });

            modelBuilder.Entity("EFCoreCodeFirstOneToManyDZ.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EFCoreCodeFirstOneToManyDZ.Models.Order", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EFCoreCodeFirstOneToManyDZ.Models.Producer", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EFCoreCodeFirstOneToManyDZ.Models.Product", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("EFCoreCodeFirstOneToManyDZ.Models.Review", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
